name: 'dbt_citibike'
version: '1.0.0'
config-version: 2

profile: 'citibike'

model-paths: ["models"]
analysis-paths: ["analyses"]
seed-paths: ["seed"]
macro-paths: ["macro"]
snapshot-paths: ["snapshots"]




target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_citibike:
    staging:
      materialized: view
    core:
      materialized: table

