version: 2

models:
  - name: ride_station
    description: "Combine ride records with station catalog data for complete geographic insights."
    columns:
      - name: ride_id
        description: "Unique identifier for the ride"
      - name: origin_station_id
        descriptin: "ID for the start station"
      - name: origin_station_name
        descriptin: "Name of the origin station"
      - name: destination_station_id
        descriptin: "ID for the destination station"
      - name: destination_station_name
        descriptin: "Name of the destination station"
      - name: origin_datetime
        descriptin: "Datetime when the ride started"
      - name: destination_datetime
        descriptin: "Datetime when the ride ended"
      - name: ride_duration_minutes
        descriptin: "Duration of the ride in minutes"
      - name: ride_quality_flag
        descriptin: "Categorizes rides by duration and datetime consistency"
      

