version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'data-kestra1.ny_citi_bike') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'ny_citi_bike') }}"
    tables:
      - name: citibike_tripdata
        description: "Raw rides data loaded via kestra. This is the starting point for ride enrichment."

models:
  - name: stg_citibike_tripdata
    description: "Processed ride records containing structured datetime fields, rider information, and derived duration metrics."
    columns:
      - name: ride_id
        description: "Unique identifier for each ride"
      - name: origin_datetime
        description: "Datetime when the ride started, processed from origin date and time"
      - name: destination_datetime
        description: "Datetime when the ride ended, processed from destination date and time"
      - name: ride_duration_minutes
        description: "Total duration of the ride in minutes"
      - name: user_age
        description: "Age of the user at time of the ride"
      - name: user_gender
        description: "Gender of the user, as recorded in the original dataset"
      - name: origin_station_id
        description: "Station ID where the ride started"
      - name: destination_station_id
        description: "Station ID where the ride ended"

  - name: stg_stations
    description: "Clean representation of the Citibike station catalog as received in the raw data"
    columns:
      - name: station_id
        description: "Unique identifier of the station"
      - name: name
        description: "Station name"
      - name: short_name
        description: "Short version of the station name"
      - name: lat
        description: "Latitude of the station location"
      - name: lon
        description: "Longitude of the station location"
      - name: capacity
        description: "Total number of docking points"
      - name: is_charging
        description: "Whether the station supports electric bike charging"
      - name: has_kiosk
        description: "Whether the station has a kiosk interface"
      - name: ingestion_ts
        description: "Timestamp of when the station data was ingested into the system"